# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStorageAttachments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1)),
                ('record_type', models.CharField(max_length=1)),
                ('record_id', models.BigIntegerField()),
                ('blob_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'active_storage_attachments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveStorageBlobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=1, unique=True)),
                ('filename', models.CharField(max_length=1)),
                ('content_type', models.CharField(blank=True, max_length=1, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('byte_size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'active_storage_blobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArInternalMetadata',
            fields=[
                ('key', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ar_internal_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'course_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('url', models.CharField(blank=True, max_length=1, null=True)),
                ('course_load', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ead_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OauthAccessGrants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_owner_id', models.IntegerField()),
                ('token', models.CharField(max_length=1, unique=True)),
                ('expires_in', models.IntegerField()),
                ('redirect_uri', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'oauth_access_grants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OauthAccessTokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_owner_id', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=1, unique=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1, null=True, unique=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('scopes', models.CharField(blank=True, max_length=1, null=True)),
                ('previous_refresh_token', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'oauth_access_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OauthApplications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1)),
                ('uid', models.CharField(max_length=1, unique=True)),
                ('secret', models.CharField(max_length=1)),
                ('redirect_uri', models.TextField()),
                ('scopes', models.CharField(max_length=1)),
                ('confidential', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth_applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OauthOpenidRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'oauth_openid_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaMigrations',
            fields=[
                ('version', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'schema_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1, null=True)),
                ('url', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=1)),
                ('cpf', models.CharField(max_length=1)),
                ('first_name', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=1, null=True)),
                ('crypted_password', models.CharField(blank=True, max_length=1, null=True)),
                ('salt', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_logout_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_from_ip_address', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
