# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('course_category', models.CharField(max_length=100, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
    ]
