# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='date',
        ),
    ]
