# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0003_auto_20180920_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
