# Generated by Django 2.1.1 on 2018-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0005_auto_20180920_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactus',
            name='course_category_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='course_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='school_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
