# Generated by Django 2.1.3 on 2018-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0008_auto_20181127_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contact_us_messages',
        ),
    ]
