# Generated by Django 2.1.3 on 2018-11-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0009_auto_20181127_1436'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='evl_profiles',
        ),
    ]
