# Generated by Django 2.1.3 on 2018-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0010_auto_20181127_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(default='sadadsad', max_length=100),
            preserve_default=False,
        ),
    ]
