# Generated by Django 2.1.3 on 2019-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evl', '0011_profile_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
